# Use the official MariaDB image as the base
FROM mariadb:latest

# Set the root password for MariaDB
ENV MYSQL_ROOT_PASSWORD=risingsun

# Copy the backup script into the Docker image
COPY backup-042024.sql /docker-entrypoint-initdb.d/
