# Use the official MariaDB image as the base
FROM mariadb:latest

# Set the root password for MariaDB
ENV MARIADB_ROOT_PASSWORD=risingsun
ENV MARIADB_AUTO_UPGRADE=1

# enable remote network access
COPY .my.cnf /root/

# set the location of the data
# VOLUME /home/backup/DockerData/mysql

# Copy the backup script into the Docker image -- no longer needed
# COPY mysql.sql /docker-entrypoint-initdb.d/
